FROM alpine:3.9

MAINTAINER docker@stefan-van-essen.nl

ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' TERM='xterm'

ADD https://php.codecasts.rocks/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN apk --update add ca-certificates \
    && echo "@php https://php.codecasts.rocks/v3.9/php-7.3" >> /etc/apk/repositories \
    && apk -U --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    build-base \
    bash \
    curl \
    docker \
    git \
    g++ \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libtool \
    libwebp \
    libwebp-dev \
    make \
    nasm \
    nodejs \
    nodejs-npm \
    openssh \
    php7@php \
    php7-ctype@php \
    php7-curl@php \
    php7-dom@php \
    php7-gettext@php \
    php7-gd@php \
    php7-gmp@php \
    php7-iconv@php \
    php7-json@php \
    php7-ldap@php \
    php7-mbstring@php \
    php7-openssl@php \
    php7-pcntl@php \
    php7-pdo_mysql@php \
    php7-pdo_pgsql@php \
    php7-pdo_sqlite@php \
    php7-phar@php \
    php7-posix@php \
    php7-redis@php \
    php7-session@php \
    php7-soap@php \
    php7-xdebug@php \
    php7-xml@php \
    php7-xmlreader@php \
    php7-zip@php \
    php7-zlib@php \
    zlib-dev@php \
    && ln -s /usr/bin/php7 /usr/bin/php \
    && curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && npm install -g yarn

COPY cache-tool.sh /usr/local/bin/cache-tool

# Temporary workaround for problems with php-iconv on Alpine based PHP images
# See https://github.com/docker-library/php/issues/240 for more info
RUN apk add gnu-libiconv --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
ENV LD_PRELOAD='/usr/lib/preloadable_libiconv.so php'
