FROM alpine:3.5

LABEL maintainer="docker@stefan-van-essen.nl"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' TERM='xterm'

# Temporary workaround for problems with php7-iconv on Alpine based PHP images
# See https://github.com/docker-library/php/issues/240 for more info
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/community/ gnu-libiconv=1.15-r2
ENV LD_PRELOAD='/usr/lib/preloadable_libiconv.so php'
ENV MUSL_LOCPATH /usr/share/i18n/locales/musl

RUN apk -U --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    build-base \
    bash \
    curl \
    cmake \
    docker \
    gettext-dev \
    git \
    g++ \
    gcc \
    libintl \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libtool \
    libwebp \
    libwebp-dev \
    make \
    musl-dev \
    nasm \
    nodejs \
    openssh \
    php5 \
    php5-openssl \
    php5-ctype \
    php5-curl \
    php5-dom \
    php5-gettext \
    php5-gd \
    php5-gmp \
    php5-iconv \
    php5-intl \
    php5-json \
    php5-ldap \
    php5-mcrypt \
    php5-pcntl \
    php5-pdo_mysql \
    php5-pdo_pgsql \
    php5-pdo_sqlite \
    php5-phar \
    php5-posix \
    php5-snmp \
    php5-soap \
    php5-xdebug \
    php5-xml \
    php5-xmlreader \
    php5-zip \
    php5-zlib \
    zlib-dev \
    && curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && npm install -g --unsafe-perm yarn \
    && sed -i 's/;zend/zend/g' /etc/php5/conf.d/xdebug.ini \
    && curl https://gitlab.com/rilian-la-te/musl-locales/-/archive/master/musl-locales-master.zip --output musl-locales-master.zip \
    && unzip musl-locales-master.zip \
      && cd musl-locales-master \
      && cmake -DLOCALE_PROFILE=OFF -D CMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install \
      && cd .. && rm -r musl-locales-master

COPY cache-tool.sh /usr/local/bin/cache-tool
