FROM alpine:3.9

MAINTAINER docker@stefan-van-essen.nl

ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' TERM='xterm'

ADD https://dl.bintray.com/php-alpine/key/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN apk --update add ca-certificates \
    && echo "https://dl.bintray.com/php-alpine/v3.9/php-7.3" >> /etc/apk/repositories \
    && apk -U --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    build-base \
    bash \
    curl \
    docker \
    git \
    g++ \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libtool \
    libwebp \
    libwebp-dev \
    make \
    nasm \
    nodejs \
    nodejs-npm \
    openssh \
    php \
    php-ctype \
    php-curl \
    php-dom \
    php-gettext \
    php-gd \
    php-gmp \
    php-iconv \
    php-json \
    php-ldap \
    php-mbstring \
    php-openssl \
    php-pcntl \
    php-pdo_mysql \
    php-pdo_pgsql \
    php-pdo_sqlite \
    php-phar \
    php-posix \
    php-redis \
    php-session \
    php-soap \
    php-xdebug \
    php-xml \
    php-xmlreader \
    php-zip \
    php-zlib \
    zlib-dev \
    && ln -s /usr/bin/php7 /usr/bin/php \
    && curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && npm install -g yarn

COPY cache-tool.sh /usr/local/bin/cache-tool

# Temporary workaround for problems with php-iconv on Alpine based PHP images
# See https://github.com/docker-library/php/issues/240 for more info
RUN apk add gnu-libiconv --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/
ENV LD_PRELOAD='/usr/lib/preloadable_libiconv.so php'
