FROM alpine:3.5

MAINTAINER docker@stefan-van-essen.nl

ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' TERM='xterm' DOCKER_HOST='docker'

RUN apk -U --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    build-base \
    bash \
    curl \
    docker \
    git \
    g++ \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libwebp \
    libwebp-dev \
    make \
    nasm \
    nodejs \
    openssh \
    php5 \
    php5-openssl \
    php5-ctype \
    php5-curl \
    php5-dom \
    php5-gettext \
    php5-gd \
    php5-gmp \
    php5-iconv \
    php5-intl \
    php5-json \
    php5-ldap \
    php5-mcrypt \
    php5-pcntl \
    php5-pdo_mysql \
    php5-pdo_pgsql \
    php5-pdo_sqlite \
    php5-phar \
    php5-snmp \
    php5-xdebug \
    php5-xml \
    php5-xmlreader \
    php5-zip \
    php5-zlib \
    zlib-dev \
    && curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && npm install -g yarn \
    && sed -i 's/;zend/zend/g' /etc/php5/conf.d/xdebug.ini

COPY cache-tool.sh /usr/local/bin/cache-tool
