FROM alpine:3.5

LABEL maintainer="docker@stefan-van-essen.nl"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' TERM='xterm'

# Temporary workaround for problems with php7-iconv on Alpine based PHP images
# See https://github.com/docker-library/php/issues/240 for more info
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.12/community/ gnu-libiconv=1.15-r2
ENV LD_PRELOAD='/usr/lib/preloadable_libiconv.so php'
ENV MUSL_LOCPATH /usr/share/i18n/locales/musl

RUN apk -U --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    build-base \
    bash \
    curl \
    cmake \
    docker \
    gettext-dev \
    git \
    g++ \
    gcc \
    libintl \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libtool \
    libwebp \
    libwebp-dev \
    make \
    musl-dev \
    nasm \
    nodejs \
    openssh \
    php7 \
    php7-ctype \
    php7-curl \
    php7-dom \
    php7-ftp \
    php7-gettext \
    php7-gd \
    php7-gmp \
    php7-iconv \
    php7-intl \
    php7-json \
    php7-ldap \
    php7-mbstring \
    php7-mcrypt \
    php7-openssl \
    php7-pcntl \
    php7-pdo_mysql \
    php7-pdo_pgsql \
    php7-pdo_sqlite \
    php7-phar \
    php7-posix \
    php7-session \
    php7-snmp \
    php7-soap \
    php7-xdebug \
    php7-xml \
    php7-xmlreader \
    php7-zip \
    php7-zlib \
    zlib-dev \
    && ln -s /usr/bin/php7 /usr/bin/php \
    && curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && npm install -g --unsafe-perm yarn \
    && sed -i 's/;zend/zend/g' /etc/php7/conf.d/xdebug.ini \
    && unzip musl-locales-master.zip \
      && cd musl-locales-master \
      && cmake -DLOCALE_PROFILE=OFF -D CMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install \
      && cd .. && rm -r musl-locales-master

COPY cache-tool.sh /usr/local/bin/cache-tool
