FROM alpine:3.15

LABEL maintainer="docker@stefan-van-essen.nl"

ENV LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' TERM='xterm'

# Temporary workaround for problems with php8-iconv on Alpine based PHP images
# See https://github.com/docker-library/php/issues/240 for more info
ENV LD_PRELOAD='/usr/lib/preloadable_libiconv.so php'
ENV MUSL_LOCPATH /usr/share/i18n/locales/musl

ADD https://php.hernandev.com/key/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN apk -U --no-cache add ca-certificates && \
    echo "https://php.hernandev.com/v3.15/php-8.1" >> /etc/apk/repositories

RUN apk -U --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    build-base \
    bash \
    curl \
    cmake \
    docker \
    gcc \
    gettext-dev \
    git \
    g++ \
    gnu-libiconv \
    libintl \
    libjpeg-turbo \
    libjpeg-turbo-dev \
    libpng \
    libpng-dev \
    libtool \
    libwebp \
    libwebp-dev \
    make \
    musl-dev \
    nasm \
    nodejs \
    npm \
    openssh \
    zlib-dev \
    'php8>8.1' \
    'php8-common>8.1' \
    'php8-ctype>8.1' \
    'php8-curl>8.1' \
    'php8-dom>8.1' \
    'php8-ftp>8.1' \
    'php8-gettext>8.1' \
    'php8-gd>8.1' \
    'php8-gmp>8.1' \
    'php8-iconv>8.1' \
    'php8-intl>8.1' \
    'php8-ldap>8.1' \
    'php8-mbstring>8.1' \
    'php8-openssl>8.1' \
    'php8-pcntl>8.1' \
    'php8-pdo_mysql>8.1' \
    'php8-pdo_pgsql>8.1' \
    'php8-pdo_sqlite>8.1' \
    'php8-phar>8.1' \
    'php8-posix>8.1' \
    'php8-redis' \
    'php8-session>8.1' \
    'php8-snmp>8.1' \
    'php8-soap>8.1' \
    'php8-xdebug' \
    'php8-xml>8.1' \
    'php8-xmlreader>8.1' \
    'php8-zip>8.1' \
    'php8-zlib>8.1' \
    && ln -s /usr/bin/php8 /usr/bin/php \
    && curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && npm install -g --unsafe-perm yarn \
    && sed -i 's/;zend/zend/g' /etc/php8/conf.d/50_xdebug.ini \
    && curl https://gitlab.com/rilian-la-te/musl-locales/-/archive/master/musl-locales-master.zip --output musl-locales-master.zip \
    && unzip musl-locales-master.zip \
    && cd musl-locales-master \
    && cmake -DLOCALE_PROFILE=OFF -D CMAKE_INSTALL_PREFIX:PATH=/usr . && make && make install \
    && cd .. && rm -r musl-locales-master \
    && rm musl-locales-master.zip

COPY cache-tool.sh /usr/local/bin/cache-tool
